
export const AffCodes = ["CC", "CS", "DC", "FS", "FW", "LA", "FR", "IC", "HC", "Clan", "CF", "MC", "MH", "OA", "TC", "MP", "DP", "IN", "TR", "Per"];

export const APTypes = ["Ballistic", "Energy", "Melee", "Special", "Explosive"];

export const DamageTypes = ["Area-Effect", "Burst-Fire", "Continuous", "Subduing", "Splash"];

export const Skills = [
    "Acrobatics/Freefall",
    "Acrobatics/Gymnastics",
    "Acting",
    "Administration",
    "Animal Handling/Herding",
    "Animal Handling/Riding",
    "Animal Handling/Training",
    "Appraisal",
    "Archery",
    "Art",
    "Artillery",
    "Career",
    "Climbing",
    "Communications/Black Box",
    "Communications/Conventional",
    "Communications/HPG",
    "Computers",
    "Cryptography",
    "Demolitions",
    "Disguise",
    "Driving/Ground Vehicles",
    "Driving/Rail Vehicles",
    "Driving/Sea Vehicles",
    "Escape Artist",
    "Forgery",
    "Gunnery/Aerospace",
    "Gunnery/Air Vehicles",
    "Gunnery/Battlesuit",
    "Gunnery/Ground Vehicle",
    "Gunnery/Mech",
    "Gunnery/ProtoMech",
    "Gunnery/Sea Vehicle",
    "Gunnery/Spacecraft",
    "Gunnery/Turret",
    "Interest",
    "Interrogation",
    "Investigation",
    "Language/English",
    "Language/Affiliation",
    "Leadership",
    "Martial Arts",
    "MedTech/General",
    "MedTech/Veterinary",
    "Melee Weapons",
    "Navigation/Air",
    "Navigation/Ground",
    "Navigation/K-F Jump",
    "Navigation/Sea",
    "Navigation/Space",
    "Negotiation",
    "Perception",
    "Piloting/Aerospace",
    "Piloting/Air Vehicle",
    "Piloting/Battlesuit",
    "Piloting/Mech",
    "Piloting/ProtoMech",
    "Piloting/Spacecraft",
    "Prestidigitation/PickPocket",
    "Prestidigitation/Quickdraw",
    "Prestidigitation/Sleight of Hand",
    "Protocol",
    "Running",
    "Science",
    "Security Systems/Electronic",
    "Security Systems/Mechanical",
    "Sensor Operations",
    "Small Arms",
    "Stealth",
    "Strategy",
    "Streetwise",
    "Support Weapons",
    "Surgery/General",
    "Surgery/Veterinary",
    "Survival",
    "Swimming",
    "Tactics/Infantry",
    "Tactics/Land",
    "Tactics/Sea",
    "Tactics/Air",
    "Tactics/Space",
    "Technician/Aeronautics",
    "Technician/Cybernetics",
    "Technician/Electronic",
    "Technician/Jets",
    "Technician/Mechanical",
    "Technician/Myomer",
    "Technician/Nuclear",
    "Technician/Weapons",
    "Thrown Weapons/Blades",
    "Thrown Weapons/Blunt Weapons",
    "Tracking/Urban",
    "Tracking/Wilds",
    "Training",
    "Zero-G Operations"
];